export const EXERCISE_LIBRARY = [
  {
    group: "Chest",
    exercises: [
      "Barbell Bench Press",
      "Incline Barbell Press",
      "Decline Barbell Press",
      "Dumbbell Bench Press",
      "Incline Dumbbell Press",
      "Dumbbell Fly",
      "Cable Fly",
      "Pec Deck",
      "Push-Ups",
      "Dips",
      "Smith Machine Bench Press",
    ],
  },
  {
    group: "Back",
    exercises: [
      "Deadlift",
      "Barbell Row",
      "Dumbbell Row",
      "Pull-Ups",
      "Chin-Ups",
      "Lat Pulldown",
      "Close Grip Lat Pulldown",
      "Seated Cable Row",
      "T-Bar Row",
      "Seated Row Machine",
      "Face Pull",
      "Hyperextension",
    ],
  },
  {
    group: "Shoulders",
    exercises: [
      "Barbell Overhead Press",
      "Dumbbell Shoulder Press",
      "Smith Machine Shoulder Press",
      "Lateral Raise",
      "Cable Lateral Raise",
      "Front Raise",
      "Rear Delt Fly",
      "Arnold Press",
      "Upright Row",
      "Shrugs",
    ],
  },
  {
    group: "Arms",
    exercises: [
      "Barbell Curl",
      "Dumbbell Curl",
      "Hammer Curl",
      "Preacher Curl",
      "Cable Curl",
      "Concentration Curl",
      "EZ-Bar Curl",
      "Rope Pushdown",
      "Bar Pushdown",
      "Skull Crushers",
      "Overhead Tricep Extension",
      "Close-Grip Bench Press",
      "Cable Overhead Extension",
    ],
  },
  {
    group: "Legs",
    exercises: [
      "Barbell Squat",
      "Goblet Squat",
      "Hack Squat",
      "Leg Press",
      "Leg Extension",
      "Leg Curl",
      "Romanian Deadlift",
      "Stiff-Leg Deadlift",
      "Lunges",
      "Bulgarian Split Squat",
      "Calf Raise",
      "Seated Calf Raise",
    ],
  },
  {
    group: "Glutes",
    exercises: [
      "Hip Thrust",
      "Glute Bridge",
      "Cable Kickback",
      "Donkey Kick",
      "Romanian Deadlift",
      "Bulgarian Split Squat",
    ],
  },
  {
    group: "Core",
    exercises: [
      "Plank",
      "Cable Crunch",
      "Hanging Leg Raise",
      "Ab Wheel Rollout",
      "Russian Twist",
      "Decline Sit-Up",
      "Leg Raise",
    ],
  },
];

export const ALL_GROUPS = EXERCISE_LIBRARY.map(g => g.group);
