export const SEED_EXERCISES = [
  // Push
  { name: "Incline Bar Bench", category: "Push" },
  { name: "Flat Bar Bench", category: "Push" },
  { name: "Smith Shoulder Press", category: "Push" },
  { name: "Cable Lateral Raise", category: "Push" },
  { name: "Dips", category: "Push" },
  { name: "Pec Fly", category: "Push" },
  { name: "Rope Pushdown", category: "Push" },
  { name: "Tricep Extension", category: "Push" },
  // Pull
  { name: "Lat Pulldown", category: "Pull" },
  { name: "Close Lat Pulldown", category: "Pull" },
  { name: "Close Lat Pulldown Cable", category: "Pull" },
  { name: "Wide Row Machine", category: "Pull" },
  { name: "Close Row Cable", category: "Pull" },
  { name: "Close Row Machine", category: "Pull" },
  { name: "T Bar Row", category: "Pull" },
  { name: "Barbell Row Machine", category: "Pull" },
  { name: "Rear Deltoid", category: "Pull" },
  // Leg
  { name: "Leg Curl", category: "Leg" },
  { name: "Leg Extension", category: "Leg" },
  { name: "Leg Press", category: "Leg" },
  { name: "Deadlift", category: "Leg" },
  { name: "Glute", category: "Leg" },
  { name: "Squat", category: "Leg" },
];

export const FUNNY_MESSAGES = [
  "PAIN IS JUST WEAKNESS LEAVING YOUR BODY. OR IT'S AN INJURY. GET IT CHECKED.",
  "YOUR FUTURE SELF IS WATCHING. THEY LOOK GREAT. KEEP GOING.",
  "THE IRON DOESN'T CARE ABOUT YOUR EXCUSES. NEITHER DOES YOUR MIRROR.",
  "YOU JUST DID MORE THAN 90% OF PEOPLE DID TODAY. THE OTHER 10% ARE ALSO HERE.",
  "REST PERIOD: CONTEMPLATE WHY YOU CHOSE THIS LIFESTYLE. THEN DO ANOTHER SET.",
  "MUSCLE SORENESS TOMORROW IS TOMORROW'S PROBLEM. TODAY'S PROBLEM IS THIS REP.",
  "YOU CAME. YOU LIFTED. YOU WILL BE SORE. WORTH IT.",
  "TECHNICALLY YOU COULD STOP NOW. BUT YOU WON'T. BECAUSE YOU'RE NOT BUILT THAT WAY.",
  "EVERY PLATE YOU ADD IS A CONVERSATION WITH GRAVITY. GRAVITY IS LISTENING.",
  "THE GYM IS THE ONE PLACE WHERE SUFFERING IS THE POINT. YOU'RE DOING GREAT.",
];

export const MOTIVATIONAL_PHRASES = [
  "YOU GOT THIS",
  "PUSH HARDER",
  "NO PAIN NO GAIN",
  "GRIND TIME",
  "STAY HUNGRY",
  "BEAST MODE",
  "KEEP GOING",
  "MAKE IT COUNT",
  "GO GET 'EM",
  "DOMINATE",
  "YOU ARE STRONG",
  "STRONGER EVERY DAY",
  "NO SHORTCUTS",
  "DISCIPLINE IS FREEDOM",
  "PROGRESS NOT PERFECTION",
  "ONE MORE REP",
  "EARN YOUR REST",
  "YOU VS. YESTERDAY",
  "TRUST THE PROCESS",
  "DON'T QUIT",
  "SWEAT IS FAT CRYING",
  "STAY THE COURSE",
  "OUTWORK EVERYONE",
  "BUILT DIFFERENT",
  "LEVEL UP",
  "NO DAYS OFF",
  "RISE AND GRIND",
  "LIMIT DOES NOT EXIST",
  "SHOW UP. EVERY TIME.",
  "HUNGER OVER TALENT",
];
